### ISSUE TITLE
Schedule Map Error on Omeka 

### ISSUE THREAD

**Issue by csgreer6** [religious-ecologies/omeka-s-theme#10]
The Schedule Map tab on Omeka pulls nothing up but an error message. It may not be ready yet but I wanted y'all to be aware. Image attached. On a Mac.
![Screen Shot 2020-10-29 at 1 30 38 PM](https://user-images.githubusercontent.com/70596028/97610285-0eb9d200-19eb-11eb-839e-583909805d2f.png)

**Comment by kimisgold** [comment]
This is a permissions issue, now fixed in https://github.com/chnm/Mare-module/commit/07b0965f5168b6365566680b02af2d90fce0f608.
