### ISSUE TITLE
Homepage Link has no accessible name, innerText, or [title] - ANDI

### ISSUE THREAD

**Issue by csgreer6** [religious-ecologies/omeka-s-theme#11]
Three elements on the homepage, the image with linked elements 'denomination,' 'counties,' and 'schedules,' have no accessible name, etc.

Images:
![Screen Shot 2020-10-29 at 1 40 12 PM](https://user-images.githubusercontent.com/70596028/97611270-52f9a200-19ec-11eb-84b8-5bd59b6f63a6.png)
![Screen Shot 2020-10-29 at 1 40 23 PM](https://user-images.githubusercontent.com/70596028/97611322-6442ae80-19ec-11eb-906b-c68e41da68ef.png)

**Comment by kimisgold** [comment]
The markup now better groups the image and its title within the link.
