### ISSUE TITLE
Keyboard Access Alerts ANDI

### ISSUE THREAD

**Issue by csgreer6** [religious-ecologies/omeka-s-theme#13]
On the Items page, the omeka items have keyboard access alerts stating that they may only be clicked on with a mouse. ANDI on Mac.

(note: I used the trackpad on my laptop and could click them but was unsure if that was the same thing or not).

Image:
![Screen Shot 2020-10-29 at 1 43 12 PM](https://user-images.githubusercontent.com/70596028/97611791-04003c80-19ed-11eb-89af-5b6c3360dc84.png)

**Comment by kimisgold** [comment]
This seems an odd one because ANDI clearly catches the href while claiming that the links don't have hrefs. WAVE doesn't throw any alerts for these either. I'm going to chalk this one up to a bug on ANDI's side.
