### ISSUE TITLE
Skipped heading level on home page

### ISSUE THREAD

**Issue by jhammo3** [religious-ecologies/omeka-s-theme#15]
Using a Mac Book Pro on Firefox, WAVE shows that the heading, "The Census Bureau and American Congregations," is classified as a heading 3 while "The 1926 U.S. Census of Religious Bodies" shows as heading 1. Thus, there is a skipped heading level — number 2.
<img width="642" alt="Screen Shot 2020-10-29 at 1 46 16 PM" src="https://user-images.githubusercontent.com/73657683/97612634-0ca54280-19ee-11eb-970a-40224c754a77.png">

**Comment by kimisgold** [comment]
This has been fixed within the content.
