### ISSUE TITLE
Skipped heading levels on browse page

### ISSUE THREAD

**Issue by jhammo3** [religious-ecologies/omeka-s-theme#17]
On Mac Book Pro on Firefox, WAVE shows that the "browse" page contains heading levels 1 and 2 but then skips to levels 4 and 5. 
<img width="707" alt="Screen Shot 2020-10-29 at 2 29 15 PM" src="https://user-images.githubusercontent.com/73657683/97616725-4e84b780-19f3-11eb-978b-fb01b9d5d7a4.png">

**Comment by kimisgold** [comment]
This is handled in the Browse Filter module. Fieldsets and legends are more appropriate here, and the markup has been updated accordingly in https://github.com/religious-ecologies/mare-browse-filters/commit/ad3a700b25da5d2222891cd1f5a482d4b518f680.
