### ISSUE TITLE
home page - redundant links

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#18]
https://omeka.religiousecologies.org/s/census-1926/page/home

WAVE is alerting to the 3 large images on this page as having redundant links. I'm thinking this has to do with the text links on top of them and the image links being the same.
![Screen Shot 2020-11-02 at 12 05 18 PM](https://user-images.githubusercontent.com/618307/97897057-f0621800-1d03-11eb-871e-e47b4ccd1e90.png)

**Comment by kimisgold** [comment]
I think this was resolved in 7741a12.
