### ISSUE TITLE
browse page - dropdowns without accessible names and form labels

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#22]
ANDI is alerting to the two "Select filter" dropdowns as not having accessible names or titles. WAVE shows they are missing form labels.
![Screen Shot 2020-11-02 at 2 44 15 PM](https://user-images.githubusercontent.com/618307/97912053-404bd980-1d1a-11eb-8985-918269dd8078.png)

**Comment by kimisgold** [comment]
This is basically a dupe of #24, so I'll close this and keep the other open until resolved.
