### ISSUE TITLE
browse page - redundant link on nbc image 

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#23]
WAVE is alerting to the below image as having a redundant link
![Screen Shot 2020-11-02 at 2 48 30 PM](https://user-images.githubusercontent.com/618307/97912480-e0096780-1d1a-11eb-93dd-a1c213ba867c.png)

ANDI is also alerting to the below and I think they might be related.
![Screen Shot 2020-11-02 at 3 46 45 PM](https://user-images.githubusercontent.com/618307/97917583-ab011300-1d22-11eb-8fad-5f5a4f45d537.png)

**Comment by kimisgold** [comment]
This might have been resolved as a side effect of 7fe76ed. Can you check @IdaAkiwumi ?
