### ISSUE TITLE
browse page - color contrast on filters

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#26]
The dropdown texts "Select a filter" is throwing 4 alerts on ANDI about contrast. For 2 alerts (text in dropdown) maybe the text should be a darker grey/black or the background should be a lighter grey/white.

The other 2 alerts have to do with the outline of the dropdowns when they are tabbed over.
![Screen Shot 2020-11-02 at 4 18 28 PM](https://user-images.githubusercontent.com/618307/97920722-df2b0280-1d27-11eb-9c9d-eada7a50852c.png)

**Comment by kimisgold** [comment]
I overrode the plugin's styles to use the default black for better contrast. Changes should be live.
