### ISSUE TITLE
browse page - sort by title mix

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#27]
When I click sort by title, at least on the Southern Baptist Convention filter, there is one image which has 99 in the name, but it's in between 990 and 989. Not sure if this mixup is happening with many others or if it's just this one.
![Screen Shot 2020-11-02 at 4 54 23 PM](https://user-images.githubusercontent.com/618307/97923565-30d58c00-1d2c-11eb-9e6d-38dfee2673c9.png)

**Comment by kimisgold** [comment]
That's unfortunately how alphabetical sorting works on text. It's reading "Southern Baptist Convention: 99" as "99_" instead of "_99" if that makes sense. It's a common issue that you can't really do anything about without structuring those titles differently.
