### ISSUE TITLE
homepage - redundant link on page name at top left

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#28]
https://omeka.religiousecologies.org/s/census-1926/page/home

WAVE is alerting to the h1
![Screen Shot 2020-11-04 at 3 15 23 PM](https://user-images.githubusercontent.com/618307/98163275-981c4900-1eb0-11eb-8062-1389aa996caa.png)
 heading link as having redundant links.

**Comment by kimisgold** [comment]
One of these headings is for the mobile menu, and the other is for the desktop. You can only see one of them with styles off because it is hidden with CSS while the other menu is active. Screen readers won't be able to catch the duplicate heading.
