### ISSUE TITLE
homepage -- image on top of main header

### ISSUE THREAD

**Issue by jgturner52** [religious-ecologies/omeka-s-theme#29]
At least when I look at it on my browser, the photograph/link to "Denominations" obscures a portion of the main header text.
![image](https://user-images.githubusercontent.com/55842785/98288215-869c7500-1f74-11eb-8344-974fe29cf2e5.png)
I am attempting to paste in a screenshot.

**Comment by kimisgold** [comment]
I've bumped down the size of that heading as well as tweaked some the layout to avoid this kind of overlap.
