### ISSUE TITLE
browse page - advanced search focus border not compact

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#31]
The border stretches too far to the right on empty space like this when tabbing:

![Screen Shot 2020-11-05 at 3 24 41 PM](https://user-images.githubusercontent.com/618307/98299516-d2a3e580-1f85-11eb-8c5a-292af251a0b2.png)

**Comment by kimisgold** [comment]
I had previously set fixed percentage widths for the main sections of the browse controls, but they should now use automatic widths and maximum percentage caps. Live on the site.
