### ISSUE TITLE
mobile -denominations - render blocking resources affecting load time

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#35]
The following URLs are causing slow load times here https://omeka.religiousecologies.org/s/census-1926/item-set/3330 according to Lighthouse:

1. https://omeka.religiousecologies.org/application/asset/css/iconfonts.css?v=2.0.1
2. https://omeka.religiousecologies.org/themes/foundation/asset/css/are.css?v=0.2
3. https://omeka.religiousecologies.org/application/asset/vendor/chosen-js/chosen.css?v=2.0.1
4. https://omeka.religiousecologies.org/s/census-1926/css-editor
5. https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
6. https://omeka.religiousecologies.org/application/asset/js/global.js?v=2.0.1
7. https://cdn.jsdelivr.net/npm/foundation-sites@6.5.3/dist/js/foundation.min.js
8. https://omeka.religiousecologies.org/themes/foundation/asset/js/are.js?v=0.2
9. https://omeka.religiousecologies.org/modules/MareBrowseFilters/asset/js/are-item-browse.js?v=0.1
10. https://omeka.religiousecologies.org/application/asset/js/chosen-options.js?v=2.0.1
11. https://omeka.religiousecologies.org/application/asset/vendor/chosen-js/chosen.jquery.js?v=2.0.1
12. https://omeka.religiousecologies.org/themes/foundation/asset/js/browse.js?v=0.2

<img width="691" alt="Screen Shot 2020-11-09 at 4 04 58 PM" src="https://user-images.githubusercontent.com/618307/98598913-29bcf980-22a9-11eb-8b35-814a48b2a24a.png">

**Comment by kimisgold** [comment]
I've done a lot of improvements on resource loading in 84c301663b2eb5144641ef6539a78ee1a67e97a7, d79c254a888370751d47318a5a7a11b811c827f3, and 632eed2294a56c203ea50118226a427684d8a2c0. I think we're down to the most critical resources being loaded on each page. At this point the CSS could use more streamlining, but the load times are perfectly functional for launch.
