### ISSUE TITLE
mobile - denominations - remove unused CSS

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#36]
https://omeka.religiousecologies.org/s/census-1926/item-set/3330

The following links on this page apparently have unused CSS:

1. https://omeka.religiousecologies.org/themes/foundation/asset/css/are.css?v=0.2
2. https://omeka.religiousecologies.org/application/asset/css/iconfonts.css?v=2.0.1
3. https://omeka.religiousecologies.org/application/asset/vendor/chosen-js/chosen.css?v=2.0.1

<img width="711" alt="Screen Shot 2020-11-09 at 4 47 59 PM" src="https://user-images.githubusercontent.com/618307/98600319-5f62e200-22ab-11eb-946d-6433a6f5c069.png">

**Comment by kimisgold** [comment]
This should be fixed with https://github.com/religious-ecologies/mare-browse-filters/commit/de4e036e34f778c6aa4cdd5db5670d7c37149cbf.

**Comment by IdaAkiwumi** [comment]
Time is a little better now, but it's still indicating some unused CSS.

<img width="626" alt="Screen Shot 2020-11-12 at 4 29 06 PM" src="https://user-images.githubusercontent.com/618307/98998506-3b4e0d80-2504-11eb-91f6-355fb5b4f248.png">

**Comment by kimisgold** [comment]
This CSS is used across the whole site, so I'm not sure why Lighthouse is flagging them.
