### ISSUE TITLE
mobile - denominations - remove unused JavaScript

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#37]
According to lighthouse there is some unused JS code here:

https://omeka.religiousecologies.org/application/asset/vendor/chosen-js/chosen.jquery.js?v=2.0.1
https://cdn.jsdelivr.net/npm/foundation-sites@6.5.3/dist/js/foundation.min.js
https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js

**Comment by kimisgold** [comment]
This should be fixed with https://github.com/religious-ecologies/mare-browse-filters/commit/de4e036e34f778c6aa4cdd5db5670d7c37149cbf.

**Comment by IdaAkiwumi** [comment]
Seems to have improved a bit, but here's what it's showing to still have unused JS.
<img width="614" alt="Screen Shot 2020-11-13 at 9 12 07 AM" src="https://user-images.githubusercontent.com/618307/99081168-60885d80-2590-11eb-8b22-4d760e2b5c07.png">

**Comment by kimisgold** [comment]
So foundation and jquery are actually used on every page of the site, because they power the mobile navigation toggle. We also definitely use jquery on the denominations page, so I think the audit is being overzealous somehow. I'm going to call this one good in that case.
