### ISSUE TITLE
mobile - denominations - minify CSS

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#39]
According to Lighthouse:
Minifying CSS files on the link below can reduce network payload sizes.  More info [here](https://web.dev/unminified-css/?utm_source=lighthouse&utm_medium=devtools)

https://omeka.religiousecologies.org/application/asset/vendor/chosen-js/chosen.css?v=2.0.1

**Comment by kimisgold** [comment]
This should now be fixed in https://github.com/religious-ecologies/omeka-s-theme/issues/39.
