### ISSUE TITLE
Navigation menu text and order

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/omeka-s-theme#40]
This is a question that @gswain2 first thought of. 

We know that the static home page site and the Omeka site are distinct CMSes, but that's not a distinction that should matter to the user. 

We currently have these links in the navigation:

- Home (links to Omeka home page)
- Browse
- Locations
- Denominations
- Schedule Map
- American Religious Ecologies (links to project home page)

I'd suggest revising that to something like this:

- Project Home (or American Religious Ecologies home?)
- 1926 Census Overview (not quite sure about wording here)
- Denominations
- Locations
- Map of Schedules
- Browse Schedules

I could also see putting "project home" at the bottom of the list where it is currently. The order here follows the draft text in #47.

Other ideas?

**Comment by lmullen** [comment]
Current thought from meeting. Removes the Omeka home link.

- Denominations
- Locations
- Map of Schedules
- Browse Schedules
- American Religious Ecologies home

**Comment by kimisgold** [comment]
I configured the navigation to the above changes.

**Comment by lmullen** [comment]
Looks like we can close this one. Feel free to reopen if need be.
