### ISSUE TITLE
Minor dashboard number display issues

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/omeka-s-theme#42]
These are minor questions for the dashboard blocks on the Omeka home page:

- [x] Can the percentage of schedules digitized be rounded to a single decimal place?

- [x] Can we use a comma separator between the thousands in "schedules per denomination"?

**Comment by lmullen** [comment]
- [ ] The comma separator for thousands should probably be in "schedules per county" too, though none of them have a thousand yet.

**Comment by jimsafley** [comment]
Fixed in https://github.com/religious-ecologies/Mare-module/commit/8ad0eabb7afa9f8cd9cf24a75ac478d9375f609e
