### ISSUE TITLE
"Schedules" block on the home page

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/omeka-s-theme#44]
- [ ] Can we pick a different schedule to display on the home page? Unfortunately this is one of the ones that got a purple cast because of the way NARA makes us do the photographing.

- [ ] Should that "schedules" block link to the browse page from the navigation, rather than to the Schedules item set?

**Comment by kimisgold** [comment]
Yes, we can definitely choose a different schedule. Do you have one in mind?

I'm currently looking into the best way to link to those navigation items with an associated image, which isn't currently built into Omeka S. This was brought up in #32, so I'll follow up on the issue there and close this once we have our preferred schedule image.

**Comment by lmullen** [comment]
Lot of pressure! Like picking a favorite child.

How about one of these?

https://omeka.religiousecologies.org/s/census-1926/item/38711

https://omeka.religiousecologies.org/s/census-1926/item/6917

**Comment by kimisgold** [comment]
38711 it is!
