### ISSUE TITLE
mobile - denominations - webfont load

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#45]
According to Lighthouse, ensure text remains visible during webfont load
<img width="715" alt="Screen Shot 2020-11-11 at 10 55 00 AM" src="https://user-images.githubusercontent.com/618307/98833765-69502680-240c-11eb-9600-aedfcf65fdb8.png">

This is the link pertaining to the above screenshot
…fonts/fa-solid-900.woff2

**Comment by kimisgold** [comment]
The recommendation this audit tool provides asks that text is user-visible while the webfont is loading. The quick solution to satisfy this alert is to use `font-display: swap`, but I'm not sure that's actually helpful in this use case where the webfont is an iconfont. I imagine the fallback characters would be empty squares. For the time being, I've recompiled the `iconfonts.css` file to use `font-display: swap`, but I'm going to keep this open while I think on a solution that makes sense to submit to core.
