### ISSUE TITLE
Footer on Omeka site

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/omeka-s-theme#46]
The footer currently has "Powered by Omeka S," which should definitely stay. What else should go here?

How is this for a draft, borrowing from the main site?

_[American Religious Ecologies](https://religiousecologies.org)_ is generously funded in part by the [National Endowment for the Humanities](https://www.neh.gov/) and developed by the [Roy Rosenzweig Center for History and New Media](https://rrchnm.org/) at [George Mason University](https://www2.gmu.edu/). All of the census schedules on this website are in the public domain. Powered by [Omeka S](https://www2.gmu.edu/).

**Comment by kimisgold** [comment]
This looks good! I've put in this first pass, and we can update it if we refine further.

**Comment by lmullen** [comment]
@kimisgold The location of the footer seems to move around on different pages. E.g., if you think of there being three columns, on the home page is spans columns two and three, but on the denominations page it spans column three. Is that intentional?

**Comment by kimisgold** [comment]
This is ready for review.

**Comment by IdaAkiwumi** [comment]
The footer is in the same spot for most pages. On the Schedule Map page and the American Religious Ecologies pages they start in different areas of the footer. I'm not sure if those matter, but if so, I think the footer should look like how it does here: https://religiousecologies.org/

**Comment by kimisgold** [comment]
The Omeka site uses a multi-column layout that makes matching the footer width to the main site a little awkward. I'm keeping the footer width to match the main content; it shouldn't span to columns taken up by the header or a filters column that can scroll.
