### ISSUE TITLE
Omeka home page text should include some "how to use"

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/omeka-s-theme#47]
Perhaps a brief paragraph at the end about the browse interface, the maps, and the locations. How would this work?

> There are several ways of browsing the schedules from the 1926 Census of Religious Bodies. By using the denominations [LINK] you can look for congregations that were part of the 214 denominations that the Census Bureau counted. By using the locations [LINK] page you can find schedules from a particular state and county, and you can also see navigate the schedules geographically with the map of schedules [LINK]. If you have a more complex query to narrow down which schedules you want to see, use the browse interface [LINK].

**Comment by lmullen** [comment]
@kimisgold Is the text above acceptable, do you think? If so, do you want me to put this on the home page? Can't quite remember how we left this one.

**Comment by kimisgold** [comment]
This works! I'll play around with presentation for this content and get back to you for feedback.

**Comment by kimisgold** [comment]
I've restructured this paragraph into short calls to actions that better describe the links on the homepage. Having the How to Use paragraph felt text-heavy next to the introductory text, and I thought integrating this copy into the existing homepage links would better help orient the user.

**Comment by lmullen** [comment]
🚀 That seems like a good improvement, @kimisgold. I like what you did with it.
