### ISSUE TITLE
Help text for schedules map page

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/omeka-s-theme#49]
How about some text at the top of this page with some instructions:

> Click on a state and then a county to see the schedules available in a particular location. If many schedules are available, you can then use the "browse all" link to see every schedule in that location.

**Comment by jimsafley** [comment]
https://github.com/religious-ecologies/Mare-module/commit/496568493b2707b09c7cb2ddcb0a9fa351a6a779
