### ISSUE TITLE
Update listing of states/territories

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/omeka-s-theme#54]
We discussed in Slack updating the state items to include just the items that reflect the country in 1926. But let's discuss before doing that.

**Comment by lmullen** [comment]
Create an item set for just 1926 states and territories.

**Comment by gswain2** [comment]
A new item set called "States/Territories, 1926" has been created and can be pulled from for the state/territory filter on the Browse page.

**Comment by kimisgold** [comment]
Should now be fixed in https://github.com/religious-ecologies/mare-browse-filters/commit/59811c4ea47919535b87c200fabbb2e2e8704e2e.

**Comment by lmullen** [comment]
Looks good! Thanks!
