### ISSUE TITLE
Opening States/Denomination Families in Locations/Denominations Browse Pages

### ISSUE THREAD

**Issue by gswain2** [religious-ecologies/omeka-s-theme#55]
On the Denomination and Locations browse pages, when you click on a state or a denomination family, it opens up a new indented section below that lists all the counties in that state, or all denominations in that denomination family. This works great and give me what I expect to see! However, trying to close that state or denomination family and open a different one is bit more confusing. Right now, it seems like the way to close them is to click on a different state/denomination family. This closes the previous one, and opens the new one. Is this designed that way on purpose? 
If the denomination family, for example, if very small (ex. Adventists) and only contains a few denominations, this works well, as you can see the rest of the family to choose from. But if it is, for example, a state with many counties, you have to scroll down a lot to even see the other states you could pick. Would something like an accordion view be possible? So when you click on a state or denomination family, it opens to allow you to view what is inside (counties/denominations), and then if you click the state or denomination family again, it would close, and allow you to pick something else? Not a super pressing issue, but could prevent lots of scrolling.
<img width="1026" alt="Screen Shot 2020-11-11 at 12 54 40 PM" src="https://user-images.githubusercontent.com/33491847/98846595-32ced780-241d-11eb-80ab-df11fd8c8fcf.png">
<img width="1218" alt="Screen Shot 2020-11-11 at 12 55 06 PM" src="https://user-images.githubusercontent.com/33491847/98846597-32ced780-241d-11eb-9c0d-70577f2a36c4.png">

**Comment by lmullen** [comment]
Fixing as #56.
