### ISSUE TITLE
mobile - map - denominations dropdown

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#58]
I had been looking at the map so long, I couldn't put my finger on this.. The dropdown is too wide on mobile. There needs to be a way to shorten it so that the sorting arrow are also displayed on screen.

<img width="370" alt="Screen Shot 2020-11-11 at 4 33 33 PM" src="https://user-images.githubusercontent.com/618307/98866917-b4cdf900-243b-11eb-8b25-171c7b258b1d.png">

**Comment by kimisgold** [comment]
Fix from https://github.com/religious-ecologies/omeka-s-theme/commit/600c4cc72b6d1af5d4939132b444b83786f55076 now live.
