### ISSUE TITLE
Home page on my Chrome (Windows) browser

### ISSUE THREAD

**Issue by jgturner52** [religious-ecologies/omeka-s-theme#59]
Very sorry to notice another issue after our meeting today, but... When I view the home page, I see this:
<img width="960" alt="Annotation 2020-11-11 150156" src="https://user-images.githubusercontent.com/55842785/98887009-12c20700-2463-11eb-8b62-dabaf77382c4.png">
For some reason, it's pushing the "Totals" and "Schedules per County" boxes down and leaving a bunch of white space.

**Comment by IdaAkiwumi** [comment]
@jgturner52 It looks normal on my browser. I recommend doing a hard refresh, if you haven't already. CMD + SHIFT + R on Chrome and here's a link for how to do this on other browsers. https://support.planwithvoyant.com/hc/en-us/articles/360046611171-How-to-do-hard-refresh-in-Chrome-Firefox-Safari-and-Microsoft-Edge-or-Internet-Explorer

**Comment by kimisgold** [comment]
The layout plugin I'm using to manage this style of grid layout has given me this kind of bad positioning at certain widths as well. I'm looking into it.

**Comment by jgturner52** [comment]
Thanks both. I tried the hard refresh, alas without success. I run into the same problem on other browsers as well.

**Comment by kimisgold** [comment]
The plugin that I was using to manage the layout was more cumbersome than it was worth, especially with regard to accessibility. Hopefully not using it addresses this bug.
