### ISSUE TITLE
ANDI issue with tables on homepage

### ISSUE THREAD

**Issue by lbrannan-hub** [religious-ecologies/omeka-s-theme#6]
ANDI reports the tables on the homepage about schedule counts per denomination has no "scope." I'm not sure if that signals a coding issue (says a solution could be to include more <th> cells), but personally I think it might be nice to add a sentence to explain or prepare the user to view the table. Also more padding generally between the tables and images on the homepage might be more aesthetically pleasing.
<img width="1406" alt="Screen Shot 2020-10-29 at 12 19 49 PM" src="https://user-images.githubusercontent.com/60223963/97606463-33f81180-19e6-11eb-98d2-9a9d8dee86ae.png">
<img width="1282" alt="Screen Shot 2020-10-29 at 12 20 23 PM" src="https://user-images.githubusercontent.com/60223963/97606469-35c1d500-19e6-11eb-8818-a8360a944dc1.png">

**Comment by kimisgold** [comment]
This is the same as #16, but I've already started referencing that one in commits.
