### ISSUE TITLE
Links not working on Denomination and Locations page

### ISSUE THREAD

**Issue by gswain2** [religious-ecologies/omeka-s-theme#67]
(I'm not sure if this is just a bug?) On both the Locations and Denominations pages, after you open the accordions for a Denomination Family/State, the links aren't working for the Denominations/Counties.

**Comment by kimisgold** [comment]
Hard refresh and try again. I fixed this bug within the admin just before I saw this issue, so it might be a matter of emptying your browser cache.

**Comment by gswain2** [comment]
Working now. Thanks!
