### ISSUE TITLE
browse schedules - some denomination/state filters not sticking

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#70]
I didn't see this issue before, but I'm noticing that some of the filters I apply don't stay in place above the filter selections. They filter the results as intended. For example, in the below screenshot, I filtered for Protestant Episcopal Church, and the filter info doesn't show, but the results do.

<img width="1187" alt="Screen Shot 2020-12-08 at 10 47 08 AM" src="https://user-images.githubusercontent.com/618307/101506117-0e461c80-3943-11eb-9955-569d43b645e0.png">

versus the below screenshot of the Southern Baptist Convention filter:

<img width="1066" alt="Screen Shot 2020-12-08 at 10 49 51 AM" src="https://user-images.githubusercontent.com/618307/101506270-2fa70880-3943-11eb-8c8c-bbd776dd1de1.png">

This is also happening for the state/territory filters.

**Comment by kimisgold** [comment]
I removed some deprecated javascript that I think was tripping up the selected filters application. Could you see if the filters are working as they should now?

**Comment by IdaAkiwumi** [comment]
So, this seems to be working properly for the Denominations, but not the States. The below screenshot is the result of me selecting a few states and applying those filters. Under "Counties", it displays a duplicate of the filtered denominations.
<img width="961" alt="Screen Shot 2020-12-09 at 9 52 52 AM" src="https://user-images.githubusercontent.com/618307/101645663-9d673900-3a04-11eb-8ca0-ab35148a109e.png">

It looks like this when I first select the states, but the result is like the above screenshot once Apply filters is clicked.
<img width="973" alt="Screen Shot 2020-12-09 at 9 52 31 AM" src="https://user-images.githubusercontent.com/618307/101645766-bb349e00-3a04-11eb-918e-a25e3c12f43c.png">

Also, I'm noticing that when I refresh the page after removing filters and not selecting "Apply filters", the filters remain. I'm not sure if this is the behavior we want, but wanted to get your thoughts on this.

**Comment by kimisgold** [comment]
Ah, I found a typo where the view is looking for the active county ids. Should be fixed!

The apply filters behavior is intended. Basically all additional changes to the dropdown need confirmation. The active filters being automatically populated are based off the URL. We could alert the user if they try to refresh without applying changes.

**Comment by IdaAkiwumi** [comment]
Ah, this is working great! And yes, I think an alert asking the user if they truly want to refresh the page or not when they have active selected/deleted filters would help... Only because of the current behavior, because if the user deletes filters or refreshes the page when filters are already applied, the user may expect the filters to clear completely from refreshing.

These articles can help in this regard: http://web-accessibility.carnegiemuseums.org/code/alerts/ , https://www.w3.org/WAI/tutorials/forms/notifications/

So an alert dialog like this should suffice, but I defer to the rest of the team for appropriate wording in this case:
A filter was deleted/selected, but wasn't applied. Refreshing the page won't clear the filter. Do you still want to refresh?

buttons underneath: [Yes] [No]

**Comment by kimisgold** [comment]
We actually had this functionality in the Omeka admin interface already, so I copied it over to the module handling these browse filters. The user should now get a browser alert asking if they want to leave the page with unsaved changes. (This language is provided by the browser.)

**Comment by IdaAkiwumi** [comment]
This functionality works for selections, but not necessarily for deletion of a filter. Is it possible to implement this for deletions?

**Comment by kimisgold** [comment]
Good catch, [the fix for the deletions should be in now](https://github.com/religious-ecologies/mare-browse-filters/commit/f6f3c9a827e795e1db2e2179246e0b0c4fdd4cf1).
