### ISSUE TITLE
locations and denominations main browser - pagination layout

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#71]
On the website for the results in Locations and Denominations pages, the number/pagination line is a bit skewed where the "current page out of total page numbers" looks vertically laid out instead of horizontal. This looks fine on mobile though.

<img width="714" alt="Screen Shot 2020-12-08 at 10 56 59 AM" src="https://user-images.githubusercontent.com/618307/101507576-b0b2cf80-3944-11eb-8fe4-75efb6d66e0e.png">

mobile version

<img width="342" alt="Screen Shot 2020-12-08 at 10 59 23 AM" src="https://user-images.githubusercontent.com/618307/101507539-a5f83a80-3944-11eb-9b77-5af98c94c705.png">

**Comment by kimisgold** [comment]
This change is live and ready for testing.
