### ISSUE TITLE
names of files on item pages

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#72]
When using Voice Over Utility, VO reads the full file name and in some cases, the files are long characters of random letters and numbers. Is it possible to have these files renamed to exactly what the document is? I know this is quite an undertaking and each file may have to be looked at closely at some point to determine the best file name title or accessible title. 

Example: https://omeka.religiousecologies.org/s/census-1926/item/6511

<img width="446" alt="Screen Shot 2020-12-08 at 3 44 37 PM" src="https://user-images.githubusercontent.com/618307/101539535-af959880-396c-11eb-858f-a29cbf1e9a7d.png">

When VO reads the above file, it reads it as "fbdf9f2dda14e8941fed50d717359d7a5abac6ee.pdf" when it should probably say something like, "Communistic Societies Document"

**Comment by kimisgold** [comment]
I've used "Scan of [Item Title]" for the time being. This change is live.
