### ISSUE TITLE
skip to main content - tab order

### ISSUE THREAD

**Issue by IdaAkiwumi** [religious-ecologies/omeka-s-theme#74]
I think a skip to main content is needed for the site to help with keyboard navigation and what was done on https://rrchnm.org/ can be used as a guide.

**Comment by kimisgold** [comment]
This is live and ready to test.

**Comment by IdaAkiwumi** [comment]
This is looking good; however, when the Skip to main content popup has been selected, it goes to the content and VOU reads it as "empty group". Is it possible to name the "content" that has been skipped to on each page by their header title for the screen readers? 

For example on the Denominations page, the main content skipped to is the links of the denominations, so I'm thinking the title of that group could be "Census Schedules by Denomination". On the Locations pages, "Census Schedules by Location", etc.

**Comment by kimisgold** [comment]
Hmm, my intent was that the generic "Start of content" label would be an okay catchall, let me see what's going on there.

The main American Religious Ecologies site is its own repo at https://github.com/religious-ecologies/website. Please feel free to file issues there, I'll be doing some updates over the next couple days.

**Comment by kimisgold** [comment]
Voiceover should now read "Beginning of content" when jumping to the main content area. Making it more specific would be nice, but would involve a lot of specific code changes that might not be a sustainable pattern when maintaining the site.
