### ISSUE TITLE
Update Text for Navigation and Call to Action Blocks

### ISSUE THREAD

**Issue by gswain2** [religious-ecologies/omeka-s-theme#75]
We have some small text revisions that we'd like to suggest:

**Left Site Navigation**
- In the left site navigation, could we change the title of the "Browse Schedules" page to "Query Schedules" instead? We feel like this will be more understandable to users, and sets up the right exceptions when the link is followed. (@kimisgold gave us the idea for the language with her new text in the call to action block on the home page, which says "Build Queries to Browse the Schedules" which, in fact, points viewers to the same page.)  

**Call to Action Blocks on the Homepage**
- Instead of "Explore the Congregations amongst the 214 Denominations Counted in the 1926 Census", we'd like to simply say "Explore Schedules by Denomination"
- Instead of "Visualize Schedules Geographically", we'd like it to say "Locate Schedules Geographically"
- We like the text of the other two action blocks as they are: "Find Schedules by State and County" and "Build Queries to Browse the Schedules"

**Comment by kimisgold** [comment]
I have one quibble is with "Visualize" vs "Locate": I feel the verb should somehow indicate the distinction between the "Map" and "Locations" views. It doesn't have to be "visualize" per se, but I do feel like "locate" doesn't tell you how that view is different from "find schedules by state and county".

**Comment by lmullen** [comment]
That's a useful point, @kimisgold. And using the word "Map" has some value. Maybe for the call to action, "Explore map of schedules" or "Use map of schedules"? And just keep "Map of Schedules" in the sidebar? What do you think, @kimisgold and @gswain2?

**Comment by kimisgold** [comment]
I lean towards "use" to keep up variety among our calls to action.

**Comment by lmullen** [comment]
Fine by me.

**Comment by gswain2** [comment]
Would you be ok with using "locate" if we had "map" in the name? Like "Use a map to locate schedules" or "Use a map to find schedules"?

**Comment by kimisgold** [comment]
"Locate schedules on our map"?

**Comment by lmullen** [comment]
Sure that works for me.

**Comment by kimisgold** [comment]
All now applied within the Omeka admin!
