### ISSUE TITLE
Images with no alt-text or values 

### ISSUE THREAD

**Issue by csgreer6** [religious-ecologies/omeka-s-theme#8]
A number of images that I don't believe are solely decorative have no alt-text or the like throughout the site.
Homepage:
![Screen Shot 2020-10-29 at 1 24 40 PM](https://user-images.githubusercontent.com/70596028/97609574-26448b00-19ea-11eb-868b-8735b5360178.png)
![Screen Shot 2020-10-29 at 1 24 45 PM](https://user-images.githubusercontent.com/70596028/97609575-26dd2180-19ea-11eb-9a83-fd773d2723f1.png)

American Religious Ecologies 'Why' Page:
![Screen Shot 2020-10-29 at 1 13 22 PM](https://user-images.githubusercontent.com/70596028/97609231-b8985f00-19e9-11eb-949f-cac6b655726e.png)

Visualizations:
![Screen Shot 2020-10-29 at 1 07 13 PM](https://user-images.githubusercontent.com/70596028/97609265-c221c700-19e9-11eb-94a3-dc5dac3b5fae.png)
![Screen Shot 2020-10-29 at 1 14 54 PM](https://user-images.githubusercontent.com/70596028/97609333-da91e180-19e9-11eb-8377-88f1442cd53e.png)

**Comment by kimisgold** [comment]
This should now have alt text reading "Preview thumbnail for [Item set name]".
