### ISSUE TITLE
Empty Heading Level on Denominations Page

### ISSUE THREAD

**Issue by csgreer6** [religious-ecologies/omeka-s-theme#9]
I am seeing an empty heading level on the Denominations page using WAVE on a Mac. It doesn't look like an issue simply on the page but I thought it may confuse some people who use screen readers. Image following.

![Screen Shot 2020-10-29 at 1 28 28 PM](https://user-images.githubusercontent.com/70596028/97610088-d2867180-19ea-11eb-939c-2b0fa47f1c74.png)

**Comment by kimisgold** [comment]
It looks like someone left an empty h2 in the page builder. It should be removed now. @csgreer6 can you refresh and confirm?
